version: '3'
services:
  client:
    container_name: tikiapp-client
    restart: always
    build: ./client
    ports:
      - '3000:3000'
    # volumes:
    #   - ./client:/client
    links:
      - app
  app:
    container_name: tikiapp-app
    restart: always
    build: ./api
    ports:
      - '4000:4000'
    links:
      - mongo
  mongo:
    # container_name: mongo2
    image: mongo
    ports:
      - '27017:27017'
